### ISSUE TITLE
Files are being generated however cannot find the generated proto

### ISSUE THREAD

**Issue by Leylan24** [pikaju/dart-protoc-builder#11]
I run the builder, it generates succesfully however I get the following error:

```
[SEVERE] protoc_builder on lib/proto/service.proto:

FileSystemException: Cannot open file, path = 'lib/lib/config/protos/service.pb.dart' (OS Error: The system cannot find the path specified.
, errno = 3)
[INFO] 28.5s elapsed, 301/317 actions completed.
[INFO] Running build completed, took 29.1s
```

looking at the hiearchy I can see the generated files exist. 
![image](https://user-images.githubusercontent.com/25897680/202139550-b1f77b99-7689-4cec-9d9b-fd661c6d03f2.png)

This is my build.yaml:

```
targets:
  $default:
    builders:
      drift_dev:
        options:
          generate_connect_constructor: false
# generate_values_in_copy_with (defaults to true): Generates a Value<T?> instead of T?
# for nullable columns in copyWith. This allows to set columns back to null (by using Value(null)).
# Passing null was ignored before, making it impossible to set columns to null.
          generate_values_in_copy_with : false
      protoc_builder:
        options:
          # The version of the Protobuf compiler to use.
          protobuf_version: "3.19.1" # Make sure to use quotation marks.
          # The version of the Dart protoc_plugin package to use.
          protoc_plugin_version: "20.0.0" # Make sure to use quotation marks.
          # Include paths given to the Protobuf compiler during compilation.
          proto_paths:
            - "lib/proto/"
          # The root directory for generated Dart output files.
          out_dir: "lib/config/protos"
```
          
If I change my build.yaml where out_dir: "./config/protos" then no files get generated.

**Comment by BenVercammen** [comment]
Did you manage to solve this? A big red flag I notice is the double "lib" in `lib/lib/config/protos/service.pb.dart` in the `FileSystemException`. The only difference with my config, is that you don't have a `root_dir` configured. My config looks like this:
```yaml
          root_dir: "lib/proto/"
          proto_paths:
            - "lib/proto/"
          out_dir: "lib/src/gen"
```
So maybe that might do the trick for you?
