### ISSUE TITLE
Adding sources outside of build tree

### ISSUE THREAD

**Issue by mikeloomisgg** [pikaju/dart-protoc-builder#19]
Proto files are often imported from sources outside of the current dart project's build tree. I could not get protoc_builder to use sources outside of the main project root.

Is this a limitation of builder_runner, or something that could be fixed in builder.dart? I tried to understand the build input/output extensions but the documentation is pretty sparse, and if the input extensions aren't detected there is no easy way to see failures in the builder_runner logs.

Anyway, here is a simple example of the build.yaml I was trying to get to work:

```
targets:
  $default:
    sources:
      - $package$
      - lib/$lib$
      - ../proto/**
    builders:
      protoc_builder:
        options:
          protobuf_version: "3.19.1"
          protoc_plugin_version: "20.0.1"
          root_dir: "../proto/"
          proto_paths:
            - "../proto/"
          out_dir: "lib/src/generated"
          grpc: true
          use_installed_protoc: false
          precompile_protoc_plugin: false
```
