### ISSUE TITLE
Protoc Builder w/ Built Value Builder

### ISSUE THREAD

**Issue by achrafmam2** [pikaju/dart-protoc-builder#26]
When I installed the protoc builder, my Built Value classes stopped being generated.

I am using the following config.

```
targets:
  $default:
    sources:
      - $package$
      - lib/$lib$
      - proto/**
    builders:
      built_value_generator|built_value:
        generate_for:
          - lib/**.dart
      protoc_builder:
        generate_for:
          - proto/**/*.proto      
        options:
          use_installed_protoc: true
```

When I remove the `sources` field built value start working but the Protos don't get generated.

Is this a known limitation?
